[package]
name = "resize-xcursor"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.62"
byteorder = "1.4.3"
clap = { version = "3.2.17", features = ["derive"] }
xcursor = "0.3.4"

[profile.release]
lto = true
panic = 'abort'
strip = 'symbols'
